language: python

notifications:
  email: false

python:
  # - 2.7
  - 3.5
  - 3.6

install:
  - python setup.py install
  - pip install codecov pytest-cov

script: py.test gb2260 --cov=gb2260 --cov-report=term-missing

after_success:
  - coverage combine
  - codecov
